blank_issues_enabled: false
contact_links:
  - name: Edgemesh® Support
    url: mailto:support@edgemesh.com
    about: Email customer support here.
  - name: Edgemesh® Community
    url: https://discord.gg/K5ACGha
    about: Join our discord community here.
